spring:
  thymeleaf:
    mode: HTML
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://81.70.153.203:3306/RAINSTORM?useSSL=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: boy-1
    pwd: 84a84-C046c
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.luosu.blog.entity
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl